### ISSUE TITLE
Rest Operator

### ISSUE THREAD

**Issue by moshloop** [flanksource/platform-operator#29]
An operator that makes idempotent HTTP rest requests, typically to configuration endpioints e.g. Elasticsearch cluster settings, ingest pipelines

```yaml
apiVersion: platform.flanksource.com/v1
kind: Rest
spec:
     url: https://elasticsearch/_cluster/setting
     username: 
     password:
     headers:
       Content-Type: application/json
     method: POST
     body: |
        {
         "persistent" : {
               "indices.recovery.max_bytes_per_sec" : "50mb"
          }
        }
```
