### ISSUE TITLE
Platform operator 0.6.4 crashes on startup

### ISSUE THREAD

**Issue by BrendanGalloway** [flanksource/platform-operator#52]
deployed a platform operator via karina with:

```
platformOperator:
  version: v0.6.4
  args:
    enable-pod-mutations=true: true
    enable-ingress-sso: true
    namespace-tolerations-annotation: tolerations
```

The pod goes to crashloop state with the following error:
```
  Warning  Failed     21m (x4 over 21m)    kubelet,  Error: failed to create containerd task: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/manager\": stat /manager: no such file or directory": unknown
```
